VERSION = 1.0.11
QMAKE_TARGET_COMPANY = Myggiz
QMAKE_TARGET_PRODUCT = DuskScreen
QMAKE_TARGET_DESCRIPTION = DuskScreen Screenshot Tool
QMAKE_TARGET_COPYRIGHT = Copyright (C) 2008-2021 Christian Kaiser, (C) 2026 Myggiz

DEFINES += APP_VERSION=\\\"$$VERSION\\\"
